version: '3'
services:
  db:
    image: mysql:8.0
    container_name: ors-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: p-04
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
  webapp:
    build: .
    container_name: ors-webapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    
volumes:
  mysql_data: